.all: player schedule weather

player: player_stats.py
	./player_stats.py

schedule: schedule.py
	./schedule.py

weather: weather.py
	./weather.py

fantasy: fantasy.py
	./fantasy.py

merged: merged_stats.py
	./merged_stats.py